---
title: "Corruption in the lab"
author: "Fedor Anna, Mokos Judit"
date: "19/12/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Description of the experiment

Two-by-two design:
- Game type: simple game or charity game
- Simulated partner: honest partner or dishonest partner

Participants are randomly assigned to one of the four conditions:
- SH: simple game with honest partner
- SD: simple ganme with dishonest partner
- CH: charity game with honest partner
- CD: charity game with dishonest partner

Each participant plays 20 rounds of the game.A round of game consists of the following steps:
- Participant learns the reported number of the supposed partner
- Participant throws a dice
- Participant reports the number 
- Both players get paid according to the reported numbers
- In the charity game a charity foundation gets a small amount of donation

Data from participants: 20 reported numbers, Questionnaire, Finger lenghts, Saliva ???
Predictors: condition, (age, gender), ???

Data frame column names:
ID, 
Game, 
Partner, 
V1, 
V2, 
... 
V20, 
Q1, 
Q2, 
... 
Q?, 
F2, 
F4, 
S???

# Figures

## Individual behavior
These should be based on Weisel & Shalvi, 2015, Fig. S10.
One figure per participant.

## Temperature plots to demonstrate the distribution of reported numbers 
Like Weisel & Shalvi, 2015, Fig. 2, but instead of circles, each rectangle should be color coded according the number of observations within them.
One figure per condition.

# Statistics
## effect size


## random or non-random, khi square


## comparing the four group, Two-way ANOVA


## LM? 